routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('intro');
});


Route::get('vestibular', function () {
    return view('vestibular');
});

Route::get('creditoestudantil', function () {
    return view('creditoestudantil');
});

Route::get('estagio', function () {
    return view('estagio');
});

Route::get('intercambio', function () {
    return view('intercambio');
});

Route::get('convenios', function () {
    return view('convenios');
});

Route::get('laboratorios', function () {
    return view('laboratorios');
});

Route::get('biblioteca', function () {
    return view('biblioteca');
});

Route::get('linhadotempo', function () {
    return view('linhadotempo');
});

Route::get('posgraduacao', function () {
    return view('posgraduacao');
});

Route::get('ouvidoria', function () {
    return view('ouvidoria');
});

Route::get('graduacao', function () {
    return view('graduacao');
});

Route::get('unidade', function () {
    return view('unidade');
});

Route::get('intro', function () {
    return view('intro');
});


Route::get('egresso', function () {
    return view('egresso');
});



//EMITIR PDF INSCRITOS
Route::any('relatorioinscritos', 'RelatorioController@gerarelatorio')->name('relatorio.relatoriopdfinscrito');
Route::any('relatorio','RelatorioController@relatorioinscrito')->name('relatorio.relatorioinscrito');

//EMITIR PDF LEADS
Route::any('relatorioleadspdf', 'RelatorioLeadsController@gerarelatorioleads')->name('relatorio.relatoriopdfleads');
Route::any('relatorioleads','RelatorioLeadsController@relatorioleads')->name('relatorio.relatoriolead');


Route::post('enviaremail1','MailController@store')->name('mail.store1');
Route::post('enviaremail2','MailController@store2')->name('mail.store2');
Route::post('enviaremail3','MailController@store3')->name('mail.store3');

Auth::routes();
Route::get('/home', 'HomeController@index');
Route::resource('noticias', 'noticiaController');

Route::get('users/{id}/delete', 'UsersController@forceDelete');


//ROTAS BANCO/VIEW HOME
Route::get('principal','IndexController@noticia');

Route::get('upload', function () {
    return view('upload');
});


Route::get('noticia','noticiaController@noticia1');

//ROTAS BANCO/VIEW NOTICIA NOTICIA
Route::get('noticia1','noticiaController@noticia1');
Route::get('noticia2','noticiaController@noticia2');
Route::get('noticia3','noticiaController@noticia3');
Route::get('noticia4','noticiaController@noticia4');
Route::get('noticia5','noticiaController@noticia5');
Route::get('noticia6','noticiaController@noticia6');

//----------UNIDADES---------------//

//unidade2
Route::get('Alagoinhas','UnidadeAlagoinhasController@unidade');

//unidade3
Route::get('Aracaju','UnidadeAracajuController@unidade');

//unidade4
Route::get('FBTAracaju','UnidadeFBTAracajuController@unidade');

//unidade5
Route::get('Arapiraca','UnidadeArapiracaController@unidade');

//unidade6
Route::get('Barreiras','UnidadeBarreirasController@unidade');

//unidade7
Route::get('Camacari','UnidadeCamacariController@unidade');

//unidade8
Route::get('Fortaleza','UnidadeFortalezaController@unidade');

//unidade9
Route::get('Feiradesantana','UnidadeFeiradesantanaController@unidade');

//unidade10
Route::get('FBTFeiradesantana','UnidadeFBTFeiradesantanaController@unidade');

//unidade11
Route::get('Juazeiro','UnidadeJuazeiroController@unidade');

//unidade12
Route::get('Maceio','UnidadeMaceioController@unidade');

//unidade13
Route::get('Mossoro','UnidadeMossoroController@unidade');

//unidade14
Route::get('Natal','UnidadeNatalController@unidade');

//unidade15
Route::get('Parnaiba','UnidadeParnaibaController@unidade');

//unidade16
Route::get('Salvador','UnidadeSalvadorController@unidade');

//unidade17
Route::get('Teresina','UnidadeTeresinaController@unidade');





//UPLOAD DE ARQUIVOS PARA O LOCAL STORAGE
Route::post('upload','UploadController@upload');


//ROTA ENVIO FORM INSCRIÇÃO EVENTO
Route::post('inscricao', 'InscricaoController@save')->name('inscricao.save');

//INSTITUCIONAL

Route::any('institucional','InstitucionalController@unidadeCurso')->name('unicurso.show');



Auth::routes();

Route::resource('users', 'usersController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadesController');

Route::resource('noticias', 'noticiasController');

Route::resource('cursos', 'cursoController');

Route::resource('tipoCursos', 'tipo_cursoController');

Route::resource('eventos', 'eventosController');

Route::resource('tipoEventos', 'tipo_eventoController');

Route::resource('banners', 'bannersController');

Route::resource('galerias', 'galeriaController');

Route::resource('leads', 'leadsController');

Route::resource('tipoCursos', 'tipo_cursosController');

Route::resource('tipoEventos', 'tipo_eventosController');

Route::resource('inscritos', 'inscritosController');

Route::resource('campanhas', 'campanhaController');

app/Models/tipo_curso.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class tipo_curso
 * @package App\Models
 * @version November 13, 2019, 5:44 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection cursos
 * @property string tipo
 */
class tipo_curso extends Model
{
    use SoftDeletes;

    public $table = 'tipo_curso';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'tipo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tipo' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipo' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function cursos()
    {
        return $this->hasMany(\App\Models\Curso::class, 'tipo_curso_id');
    }
}

app/Models/tipo_cursos.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class tipo_cursos
 * @package App\Models
 * @version January 14, 2020, 6:29 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection cursos
 * @property string tipo
 */
class tipo_cursos extends Model
{
    use SoftDeletes;

    public $table = 'tipo_cursos';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'tipo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tipo' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipo' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function cursos()
    {
        return $this->hasMany(\App\Models\Curso::class, 'tipo_cursos_id');
    }
}

app/Tipo_curso.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Tipo_curso extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'tipo'
    ];
}

app/Http/Controllers/tipo_cursoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createtipo_cursoRequest;
use App\Http\Requests\Updatetipo_cursoRequest;
use App\Repositories\tipo_cursoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class tipo_cursoController extends AppBaseController
{
    /** @var  tipo_cursoRepository */
    private $tipoCursoRepository;

    public function __construct(tipo_cursoRepository $tipoCursoRepo)
    {
        $this->tipoCursoRepository = $tipoCursoRepo;
    }

    /**
     * Display a listing of the tipo_curso.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipoCursos = $this->tipoCursoRepository->all();

        return view('tipo_cursos.index')
            ->with('tipoCursos', $tipoCursos);
    }

    /**
     * Show the form for creating a new tipo_curso.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_cursos.create');
    }

    /**
     * Store a newly created tipo_curso in storage.
     *
     * @param Createtipo_cursoRequest $request
     *
     * @return Response
     */
    public function store(Createtipo_cursoRequest $request)
    {
        $input = $request->all();

        $tipoCurso = $this->tipoCursoRepository->create($input);

        Flash::success('Tipo Curso criado com sucesso.');

        return redirect(route('tipoCursos.index'));
    }

    /**
     * Display the specified tipo_curso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoCurso = $this->tipoCursoRepository->find($id);

        if (empty($tipoCurso)) {
            Flash::error('Tipo Curso não encontrado');

            return redirect(route('tipoCursos.index'));
        }

        return view('tipo_cursos.show')->with('tipoCurso', $tipoCurso);
    }

    /**
     * Show the form for editing the specified tipo_curso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoCurso = $this->tipoCursoRepository->find($id);

        if (empty($tipoCurso)) {
            Flash::error('Tipo Curso não encontrado');

            return redirect(route('tipoCursos.index'));
        }

        return view('tipo_cursos.edit')->with('tipoCurso', $tipoCurso);
    }

    /**
     * Update the specified tipo_curso in storage.
     *
     * @param int $id
     * @param Updatetipo_cursoRequest $request
     *
     * @return Response
     */
    public function update($id, Updatetipo_cursoRequest $request)
    {
        $tipoCurso = $this->tipoCursoRepository->find($id);

        if (empty($tipoCurso)) {
            Flash::error('Tipo Curso não encontrado');

            return redirect(route('tipoCursos.index'));
        }

        $tipoCurso = $this->tipoCursoRepository->update($request->all(), $id);

        Flash::success('Tipo Curso atualizado com sucesso.');

        return redirect(route('tipoCursos.index'));
    }

    /**
     * Remove the specified tipo_curso from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoCurso = $this->tipoCursoRepository->find($id);

        if (empty($tipoCurso)) {
            Flash::error('Tipo Curso não encontrado');

            return redirect(route('tipoCursos.index'));
        }

        $this->tipoCursoRepository->delete($id);

        Flash::success('Tipo Curso excluido com sucesso.');

        return redirect(route('tipoCursos.index'));
    }
}

app/Http/Controllers/tipo_cursosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createtipo_cursosRequest;
use App\Http\Requests\Updatetipo_cursosRequest;
use App\Repositories\tipo_cursosRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class tipo_cursosController extends AppBaseController
{
    /** @var  tipo_cursosRepository */
    private $tipoCursosRepository;

    public function __construct(tipo_cursosRepository $tipoCursosRepo)
    {
        $this->tipoCursosRepository = $tipoCursosRepo;
    }

    /**
     * Display a listing of the tipo_cursos.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipoCursos = $this->tipoCursosRepository->all();

        return view('tipo_cursos.index')
            ->with('tipoCursos', $tipoCursos);
    }

    /**
     * Show the form for creating a new tipo_cursos.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_cursos.create');
    }

    /**
     * Store a newly created tipo_cursos in storage.
     *
     * @param Createtipo_cursosRequest $request
     *
     * @return Response
     */
    public function store(Createtipo_cursosRequest $request)
    {
        $input = $request->all();

        $tipoCursos = $this->tipoCursosRepository->create($input);

        Flash::success('Tipo Cursos saved successfully.');

        return redirect(route('tipoCursos.index'));
    }

    /**
     * Display the specified tipo_cursos.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoCursos = $this->tipoCursosRepository->find($id);

        if (empty($tipoCursos)) {
            Flash::error('Tipo Cursos not found');

            return redirect(route('tipoCursos.index'));
        }

        return view('tipo_cursos.show')->with('tipoCursos', $tipoCursos);
    }

    /**
     * Show the form for editing the specified tipo_cursos.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoCursos = $this->tipoCursosRepository->find($id);

        if (empty($tipoCursos)) {
            Flash::error('Tipo Cursos not found');

            return redirect(route('tipoCursos.index'));
        }

        return view('tipo_cursos.edit')->with('tipoCursos', $tipoCursos);
    }

    /**
     * Update the specified tipo_cursos in storage.
     *
     * @param int $id
     * @param Updatetipo_cursosRequest $request
     *
     * @return Response
     */
    public function update($id, Updatetipo_cursosRequest $request)
    {
        $tipoCursos = $this->tipoCursosRepository->find($id);

        if (empty($tipoCursos)) {
            Flash::error('Tipo Cursos not found');

            return redirect(route('tipoCursos.index'));
        }

        $tipoCursos = $this->tipoCursosRepository->update($request->all(), $id);

        Flash::success('Tipo Cursos updated successfully.');

        return redirect(route('tipoCursos.index'));
    }

    /**
     * Remove the specified tipo_cursos from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoCursos = $this->tipoCursosRepository->find($id);

        if (empty($tipoCursos)) {
            Flash::error('Tipo Cursos not found');

            return redirect(route('tipoCursos.index'));
        }

        $this->tipoCursosRepository->delete($id);

        Flash::success('Tipo Cursos deleted successfully.');

        return redirect(route('tipoCursos.index'));
    }
}

resources/views/tipo_cursos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Cursos
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'tipoCursos.store']) !!}

                        @include('tipo_cursos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_cursos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Cursos
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($tipoCursos, ['route' => ['tipoCursos.update', $tipoCursos->id], 'method' => 'patch']) !!}

                        @include('tipo_cursos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/tipo_cursos/fields.blade.php
<!-- Tipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo', 'Tipo:') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Salvar', ['class' => 'btn btn-success']) !!}
    <a href="{{ route('tipoCursos.index') }}" class="btn btn-danger">Cancelar</a>
</div>

resources/views/tipo_cursos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tipo Cursos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('tipoCursos.create') }}">Adicionar novo tipo de curso</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('tipo_cursos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/tipo_cursos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Cursos
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('tipo_cursos.show_fields')
                    <a href="{{ route('tipoCursos.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_cursos/show_fields.blade.php
<!-- Tipo Field -->
<div class="form-group">
    {!! Form::label('tipo', 'Tipo:') !!}
    <p>{{ $tipoCursos->tipo }}</p>
</div>

resources/views/tipo_cursos/table.blade.php
<div class="table-responsive">
    <table class="table" id="tipoCursos-table">
        <thead>
            <tr>
                <th>Tipo</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($tipoCursos as $tipoCursos)
            <tr>
                <td>{{ $tipoCursos->tipo }}</td>
                <td>
                    {!! Form::open(['route' => ['tipoCursos.destroy', $tipoCursos->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('tipoCursos.show', [$tipoCursos->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('tipoCursos.edit', [$tipoCursos->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>