routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('intro');
});


Route::get('vestibular', function () {
    return view('vestibular');
});

Route::get('creditoestudantil', function () {
    return view('creditoestudantil');
});

Route::get('estagio', function () {
    return view('estagio');
});

Route::get('intercambio', function () {
    return view('intercambio');
});

Route::get('convenios', function () {
    return view('convenios');
});

Route::get('laboratorios', function () {
    return view('laboratorios');
});

Route::get('biblioteca', function () {
    return view('biblioteca');
});

Route::get('linhadotempo', function () {
    return view('linhadotempo');
});

Route::get('posgraduacao', function () {
    return view('posgraduacao');
});

Route::get('ouvidoria', function () {
    return view('ouvidoria');
});

Route::get('graduacao', function () {
    return view('graduacao');
});

Route::get('unidade', function () {
    return view('unidade');
});

Route::get('intro', function () {
    return view('intro');
});


Route::get('egresso', function () {
    return view('egresso');
});



//EMITIR PDF INSCRITOS
Route::any('relatorioinscritos', 'RelatorioController@gerarelatorio')->name('relatorio.relatoriopdfinscrito');
Route::any('relatorio','RelatorioController@relatorioinscrito')->name('relatorio.relatorioinscrito');

//EMITIR PDF LEADS
Route::any('relatorioleadspdf', 'RelatorioLeadsController@gerarelatorioleads')->name('relatorio.relatoriopdfleads');
Route::any('relatorioleads','RelatorioLeadsController@relatorioleads')->name('relatorio.relatoriolead');


Route::post('enviaremail1','MailController@store')->name('mail.store1');
Route::post('enviaremail2','MailController@store2')->name('mail.store2');
Route::post('enviaremail3','MailController@store3')->name('mail.store3');

Auth::routes();
Route::get('/home', 'HomeController@index');
Route::resource('noticias', 'noticiaController');

Route::get('users/{id}/delete', 'UsersController@forceDelete');


//ROTAS BANCO/VIEW HOME
Route::get('principal','IndexController@noticia');

Route::get('upload', function () {
    return view('upload');
});


Route::get('noticia','noticiaController@noticia1');

//ROTAS BANCO/VIEW NOTICIA NOTICIA
Route::get('noticia1','noticiaController@noticia1');
Route::get('noticia2','noticiaController@noticia2');
Route::get('noticia3','noticiaController@noticia3');
Route::get('noticia4','noticiaController@noticia4');
Route::get('noticia5','noticiaController@noticia5');
Route::get('noticia6','noticiaController@noticia6');

//----------UNIDADES---------------//

//unidade2
Route::get('Alagoinhas','UnidadeAlagoinhasController@unidade');

//unidade3
Route::get('Aracaju','UnidadeAracajuController@unidade');

//unidade4
Route::get('FBTAracaju','UnidadeFBTAracajuController@unidade');

//unidade5
Route::get('Arapiraca','UnidadeArapiracaController@unidade');

//unidade6
Route::get('Barreiras','UnidadeBarreirasController@unidade');

//unidade7
Route::get('Camacari','UnidadeCamacariController@unidade');

//unidade8
Route::get('Fortaleza','UnidadeFortalezaController@unidade');

//unidade9
Route::get('Feiradesantana','UnidadeFeiradesantanaController@unidade');

//unidade10
Route::get('FBTFeiradesantana','UnidadeFBTFeiradesantanaController@unidade');

//unidade11
Route::get('Juazeiro','UnidadeJuazeiroController@unidade');

//unidade12
Route::get('Maceio','UnidadeMaceioController@unidade');

//unidade13
Route::get('Mossoro','UnidadeMossoroController@unidade');

//unidade14
Route::get('Natal','UnidadeNatalController@unidade');

//unidade15
Route::get('Parnaiba','UnidadeParnaibaController@unidade');

//unidade16
Route::get('Salvador','UnidadeSalvadorController@unidade');

//unidade17
Route::get('Teresina','UnidadeTeresinaController@unidade');





//UPLOAD DE ARQUIVOS PARA O LOCAL STORAGE
Route::post('upload','UploadController@upload');


//ROTA ENVIO FORM INSCRIÇÃO EVENTO
Route::post('inscricao', 'InscricaoController@save')->name('inscricao.save');

//INSTITUCIONAL

Route::any('institucional','InstitucionalController@unidadeCurso')->name('unicurso.show');



Auth::routes();

Route::resource('users', 'usersController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadeController');

Route::resource('unidades', 'unidadesController');

Route::resource('noticias', 'noticiasController');

Route::resource('cursos', 'cursoController');

Route::resource('tipoCursos', 'tipo_cursoController');

Route::resource('eventos', 'eventosController');

Route::resource('tipoEventos', 'tipo_eventoController');

Route::resource('banners', 'bannersController');

Route::resource('galerias', 'galeriaController');

Route::resource('leads', 'leadsController');

Route::resource('tipoCursos', 'tipo_cursosController');

Route::resource('tipoEventos', 'tipo_eventosController');

Route::resource('inscritos', 'inscritosController');

Route::resource('campanhas', 'campanhaController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Portal UNIRB | Painel Adminstrativo</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

    @yield('css')
</head>
<style>
.fundo{
    background-image: url("images/dashboard.png");
  

}

</style>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper" >
        <!-- Main Header -->
        <header class="main-header" >

            <!-- Logo -->
            <a href="home" class="logo" style="background-color:#1e426e" >
           <img src="images/home/redeunirb.png" style="width:14%">
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation" style="background-color:#1e426e">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <i class="fa fa-user-circle fa-2x" aria-hidden="true" style="color:white"></i>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header" style="background-color:#1e426e">
                                <i class="fa fa-user-circle fa-5x" aria-hidden="true" style="color:white"></i>

                                    <p>
                                        {!! Auth::user()->name !!}
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <!--<div class="pull-left">
                                        <a href="/users" class="btn btn-default btn-flat">Perfil</a>
                                    </div>-->

                                    <div class="pull-left">
                                       

                                        <a href="{!! url('users') !!}" class="btn btn-default btn-flat">
                                          Perfil 
                                        </a>
                                       
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sair
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper fundo" id="teste">
     
            @yield('content')

           
        
        <!-- ./col -->
        
      </div>
      
      
        </div>

        

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright UNIRB .</strong> Todos os direitos reservados.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menumkt.blade.php
<li class="header" style="color:white">MENU MKT | COMERCIAL</li>



<li class="treeview" style="bacground-color: #000">
<a href="#">
  <i class=" fa fa-circle-o "></i>
  <span>Unidades</span>
  <span class="pull-right-container">
    <i class="fa fa-angle-left pull-right"></i>
  </span>
</a>
<ul class="treeview-menu">

<li class="{{ Request::is('noticias*') ? 'active' : '' }}">
    <a href="{!! route('noticias.index') !!}"><i class="fa fa-newspaper-o" aria-hidden="true"></i><span>&nbsp; Notícias</span></a>
</li>


<li class="{{ Request::is('eventos*') ? 'active' : '' }}">
    <a href="{!! route('eventos.index') !!}"><i class="fa fa-edit"></i><span>Eventos</span></a>
</li>

<li class="{{ Request::is('leads*') ? 'active' : '' }}">
    <a href="{!! route('leads.index') !!}"><i class="fa fa-users" aria-hidden="true"></i><span>Leads</span></a>
</li>

<li class="">
    <a href="upload"><i class="fa fa-cloud-upload" aria-hidden="true"></i><span>Upload de imagem</span></a>
</li>




</ul>

resources/views/layouts/menuti.blade.php
<li class="header" style="color:white">MENU TI</li>



<li class="treeview" style="bacground-color: #000">
<a href="#">
  <i class=" fa fa-circle-o "></i>
  <span>Administração</span>
  <span class="pull-right-container">
    <i class="fa fa-angle-left pull-right"></i>
  </span>
</a>
<ul class="treeview-menu">
<li class="{{ Request::is('unidades*') ? 'active' : '' }}">
    <a href="{!! route('unidades.index') !!}"><i class="fa fa-home" aria-hidden="true"></i><span>Unidades</span></a>
</li>
<li class="{{ Request::is('noticias*') ? 'active' : '' }}">
    <a href="{!! route('noticias.index') !!}"><i class="fa fa-newspaper-o" aria-hidden="true"></i><span> Notícias</span></a>
</li>
<li class="{{ Request::is('cursos*') ? 'active' : '' }}">
    <a href="{!! route('cursos.index') !!}"><i class="fa fa-edit"></i><span>Cursos</span></a>
</li>

<li class="{{ Request::is('tipoCursos*') ? 'active' : '' }}">
    <a href="{!! route('tipoCursos.index') !!}"><i class="fa fa-edit"></i><span>Tipo dos Cursos</span></a>
</li>

<li class="{{ Request::is('eventos*') ? 'active' : '' }}">
    <a href="{!! route('eventos.index') !!}"><i class="fa fa-calendar" aria-hidden="true"></i><span>Eventos</span></a>
</li>

<li class="{{ Request::is('tipoEventos*') ? 'active' : '' }}">
    <a href="{!! route('tipoEventos.index') !!}"><i class="fa fa-calendar" aria-hidden="true"></i><span>Tipo Eventos</span></a>
</li>


<li class="{{ Request::is('banners*') ? 'active' : '' }}">
    <a href="{!! route('banners.index') !!}"><i class="fa fa-picture-o" aria-hidden="true"></i><span>Banners</span></a>
</li>
<li class="{{ Request::is('galerias*') ? 'active' : '' }}">
    <a href="{!! route('galerias.index') !!}"><i class="fa fa-picture-o" aria-hidden="true"></i><span>Galerias</span></a>
</li>

<li class="{{ Request::is('inscritos*') ? 'active' : '' }}">
    <a href="{!! route('inscritos.index') !!}"><i class="fa fa-users" aria-hidden="true"></i><span>Inscritos eventos</span></a>
</li>

<li class="{{ Request::is('leads*') ? 'active' : '' }}">
    <a href="{!! route('leads.index') !!}"><i class="fa fa-users" aria-hidden="true"></i><span>Leads</span></a>
</li>

<li class="{{ Request::is('campanhas*') ? 'active' : '' }}">
    <a href="{!! route('campanhas.index') !!}"><i class="fa fa-users" aria-hidden="true"></i><span>Campanhas</span></a>
</li>


<li class="">
    <a href="upload"><i class="fa fa-cloud-upload" aria-hidden="true"></i><span>Upload de imagem</span></a>
</li>


</ul>


<li class="treeview" style="bacground-color: #000">
<a href="#">
  <i class=" fa fa-circle-o "></i>
  <span>Configurações</span>
  <span class="pull-right-container">
    <i class="fa fa-angle-left pull-right"></i>
  </span>
</a>
<ul class="treeview-menu">
<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.index') !!}"><i class="fa fa-users" aria-hidden="true"></i><span>&nbsp;Usuários</span></a>
</li>




</ul>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
            <i class="fa fa-user-circle fa-3x" style="color:white" aria-hidden="true"></i>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <ul class="sidebar-menu" data-widget="tree">
        @if(Auth::user()->ti)
                @include('layouts.menuti')
            @else
                @if(Auth::user()->mkt)
                    @include('layouts.menumkt')
                @else
                    @include('layouts.menudefault')
                @endif
            @endif

        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>